/* This file was generated by syncqt. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.1.1"

#define ACTIVEQT_VERSION 0x050101

#endif // QT_ACTIVEQT_VERSION_H
