#############################################################################
# Makefile for building: qt
# Generated by qmake (3.0) (Qt 5.1.1) on: Tue Dec 10 15:16:43 2013
# Project:  qt.pro
# Template: subdirs
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /Users/kkheller/Documents/qt5_github_repo/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		module-qtbase \
		module-qtx11extras \
		module-qtsvg \
		module-qtactiveqt \
		module-qtsensors \
		module-qtimageformats \
		module-qtscript \
		module-qtquick1


module-qtbase-qmake_all:  FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile
	cd qtbase/ && $(MAKE) -f Makefile qmake_all
module-qtbase: FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtbase-make_first: FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtbase-all: FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtbase-clean: FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtbase-distclean: FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtbase-install_subtargets: FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtbase-uninstall_subtargets: FORCE
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
module-qtx11extras-qmake_all: module-qtbase-qmake_all FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile
	cd qtx11extras/ && $(MAKE) -f Makefile qmake_all
module-qtx11extras: module-qtbase FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtx11extras-make_first: module-qtbase-make_first FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtx11extras-all: module-qtbase-all FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtx11extras-clean: module-qtbase-clean FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtx11extras-distclean: module-qtbase-distclean FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtx11extras-install_subtargets: module-qtbase-install_subtargets FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtx11extras-uninstall_subtargets: module-qtbase-uninstall_subtargets FORCE
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
module-qtsvg-qmake_all: module-qtbase-qmake_all FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile
	cd qtsvg/ && $(MAKE) -f Makefile qmake_all
module-qtsvg: module-qtbase FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtsvg-make_first: module-qtbase-make_first FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtsvg-all: module-qtbase-all FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtsvg-clean: module-qtbase-clean FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtsvg-distclean: module-qtbase-distclean FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtsvg-install_subtargets: module-qtbase-install_subtargets FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtsvg-uninstall_subtargets: module-qtbase-uninstall_subtargets FORCE
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
module-qtactiveqt-qmake_all: module-qtbase-qmake_all FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile
	cd qtactiveqt/ && $(MAKE) -f Makefile qmake_all
module-qtactiveqt: module-qtbase FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtactiveqt-make_first: module-qtbase-make_first FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtactiveqt-all: module-qtbase-all FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtactiveqt-clean: module-qtbase-clean FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtactiveqt-distclean: module-qtbase-distclean FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtactiveqt-install_subtargets: module-qtbase-install_subtargets FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtactiveqt-uninstall_subtargets: module-qtbase-uninstall_subtargets FORCE
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
module-qtsensors-qmake_all: module-qtbase-qmake_all FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile
	cd qtsensors/ && $(MAKE) -f Makefile qmake_all
module-qtsensors: module-qtbase FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtsensors-make_first: module-qtbase-make_first FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtsensors-all: module-qtbase-all FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtsensors-clean: module-qtbase-clean FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtsensors-distclean: module-qtbase-distclean FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtsensors-install_subtargets: module-qtbase-install_subtargets FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtsensors-uninstall_subtargets: module-qtbase-uninstall_subtargets FORCE
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
module-qtimageformats-qmake_all: module-qtbase-qmake_all FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile
	cd qtimageformats/ && $(MAKE) -f Makefile qmake_all
module-qtimageformats: module-qtbase FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtimageformats-make_first: module-qtbase-make_first FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtimageformats-all: module-qtbase-all FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtimageformats-clean: module-qtbase-clean FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtimageformats-distclean: module-qtbase-distclean FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtimageformats-install_subtargets: module-qtbase-install_subtargets FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtimageformats-uninstall_subtargets: module-qtbase-uninstall_subtargets FORCE
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
module-qtscript-qmake_all: module-qtbase-qmake_all FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile
	cd qtscript/ && $(MAKE) -f Makefile qmake_all
module-qtscript: module-qtbase FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtscript-make_first: module-qtbase-make_first FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtscript-all: module-qtbase-all FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtscript-clean: module-qtbase-clean FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtscript-distclean: module-qtbase-distclean FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtscript-install_subtargets: module-qtbase-install_subtargets FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtscript-uninstall_subtargets: module-qtbase-uninstall_subtargets FORCE
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
module-qtquick1-qmake_all: module-qtscript-qmake_all module-qtsvg-qmake_all FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile
	cd qtquick1/ && $(MAKE) -f Makefile qmake_all
module-qtquick1: module-qtscript \
		module-qtsvg FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile
module-qtquick1-make_first: module-qtscript-make_first module-qtsvg-make_first FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile 
module-qtquick1-all: module-qtscript-all module-qtsvg-all FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile all
module-qtquick1-clean: module-qtscript-clean module-qtsvg-clean FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile clean
module-qtquick1-distclean: module-qtscript-distclean module-qtsvg-distclean FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile distclean
module-qtquick1-install_subtargets: module-qtscript-install_subtargets module-qtsvg-install_subtargets FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile install
module-qtquick1-uninstall_subtargets: module-qtscript-uninstall_subtargets module-qtsvg-uninstall_subtargets FORCE
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

qmake: FORCE
	@$(QMAKE) -o Makefile qt.pro

qmake_all: module-qtbase-qmake_all module-qtx11extras-qmake_all module-qtsvg-qmake_all module-qtactiveqt-qmake_all module-qtsensors-qmake_all module-qtimageformats-qmake_all module-qtscript-qmake_all module-qtquick1-qmake_all FORCE

make_first: module-qtbase-make_first module-qtx11extras-make_first module-qtsvg-make_first module-qtactiveqt-make_first module-qtsensors-make_first module-qtimageformats-make_first module-qtscript-make_first module-qtquick1-make_first FORCE
all: module-qtbase-all module-qtx11extras-all module-qtsvg-all module-qtactiveqt-all module-qtsensors-all module-qtimageformats-all module-qtscript-all module-qtquick1-all FORCE
clean: module-qtbase-clean module-qtx11extras-clean module-qtsvg-clean module-qtactiveqt-clean module-qtsensors-clean module-qtimageformats-clean module-qtscript-clean module-qtquick1-clean FORCE
distclean: module-qtbase-distclean module-qtx11extras-distclean module-qtsvg-distclean module-qtactiveqt-distclean module-qtsensors-distclean module-qtimageformats-distclean module-qtscript-distclean module-qtquick1-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: module-qtbase-install_subtargets module-qtx11extras-install_subtargets module-qtsvg-install_subtargets module-qtactiveqt-install_subtargets module-qtsensors-install_subtargets module-qtimageformats-install_subtargets module-qtscript-install_subtargets module-qtquick1-install_subtargets FORCE
uninstall_subtargets: module-qtbase-uninstall_subtargets module-qtx11extras-uninstall_subtargets module-qtsvg-uninstall_subtargets module-qtactiveqt-uninstall_subtargets module-qtsensors-uninstall_subtargets module-qtimageformats-uninstall_subtargets module-qtscript-uninstall_subtargets module-qtquick1-uninstall_subtargets FORCE

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

module-qtbase-install_html_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
module-qtx11extras-install_html_docs: module-qtbase-install_html_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
module-qtsvg-install_html_docs: module-qtbase-install_html_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
module-qtactiveqt-install_html_docs: module-qtbase-install_html_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
module-qtsensors-install_html_docs: module-qtbase-install_html_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
module-qtimageformats-install_html_docs: module-qtbase-install_html_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
module-qtscript-install_html_docs: module-qtbase-install_html_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
module-qtquick1-install_html_docs: module-qtscript-install_html_docs module-qtsvg-install_html_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
install_html_docs: module-qtbase-install_html_docs module-qtx11extras-install_html_docs module-qtsvg-install_html_docs module-qtactiveqt-install_html_docs module-qtsensors-install_html_docs module-qtimageformats-install_html_docs module-qtscript-install_html_docs module-qtquick1-install_html_docs

module-qtbase-uninstall_html_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
module-qtx11extras-uninstall_html_docs: module-qtbase-uninstall_html_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
module-qtsvg-uninstall_html_docs: module-qtbase-uninstall_html_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
module-qtactiveqt-uninstall_html_docs: module-qtbase-uninstall_html_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
module-qtsensors-uninstall_html_docs: module-qtbase-uninstall_html_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
module-qtimageformats-uninstall_html_docs: module-qtbase-uninstall_html_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
module-qtscript-uninstall_html_docs: module-qtbase-uninstall_html_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
module-qtquick1-uninstall_html_docs: module-qtscript-uninstall_html_docs module-qtsvg-uninstall_html_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
uninstall_html_docs: module-qtbase-uninstall_html_docs module-qtx11extras-uninstall_html_docs module-qtsvg-uninstall_html_docs module-qtactiveqt-uninstall_html_docs module-qtsensors-uninstall_html_docs module-qtimageformats-uninstall_html_docs module-qtscript-uninstall_html_docs module-qtquick1-uninstall_html_docs

module-qtbase-install_qch_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
module-qtx11extras-install_qch_docs: module-qtbase-install_qch_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
module-qtsvg-install_qch_docs: module-qtbase-install_qch_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
module-qtactiveqt-install_qch_docs: module-qtbase-install_qch_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
module-qtsensors-install_qch_docs: module-qtbase-install_qch_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
module-qtimageformats-install_qch_docs: module-qtbase-install_qch_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
module-qtscript-install_qch_docs: module-qtbase-install_qch_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
module-qtquick1-install_qch_docs: module-qtscript-install_qch_docs module-qtsvg-install_qch_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
install_qch_docs: module-qtbase-install_qch_docs module-qtx11extras-install_qch_docs module-qtsvg-install_qch_docs module-qtactiveqt-install_qch_docs module-qtsensors-install_qch_docs module-qtimageformats-install_qch_docs module-qtscript-install_qch_docs module-qtquick1-install_qch_docs

module-qtbase-uninstall_qch_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
module-qtx11extras-uninstall_qch_docs: module-qtbase-uninstall_qch_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
module-qtsvg-uninstall_qch_docs: module-qtbase-uninstall_qch_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
module-qtactiveqt-uninstall_qch_docs: module-qtbase-uninstall_qch_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
module-qtsensors-uninstall_qch_docs: module-qtbase-uninstall_qch_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
module-qtimageformats-uninstall_qch_docs: module-qtbase-uninstall_qch_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
module-qtscript-uninstall_qch_docs: module-qtbase-uninstall_qch_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
module-qtquick1-uninstall_qch_docs: module-qtscript-uninstall_qch_docs module-qtsvg-uninstall_qch_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
uninstall_qch_docs: module-qtbase-uninstall_qch_docs module-qtx11extras-uninstall_qch_docs module-qtsvg-uninstall_qch_docs module-qtactiveqt-uninstall_qch_docs module-qtsensors-uninstall_qch_docs module-qtimageformats-uninstall_qch_docs module-qtscript-uninstall_qch_docs module-qtquick1-uninstall_qch_docs

module-qtbase-install_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
module-qtx11extras-install_docs: module-qtbase-install_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
module-qtsvg-install_docs: module-qtbase-install_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
module-qtactiveqt-install_docs: module-qtbase-install_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
module-qtsensors-install_docs: module-qtbase-install_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
module-qtimageformats-install_docs: module-qtbase-install_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
module-qtscript-install_docs: module-qtbase-install_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
module-qtquick1-install_docs: module-qtscript-install_docs module-qtsvg-install_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
install_docs: module-qtbase-install_docs module-qtx11extras-install_docs module-qtsvg-install_docs module-qtactiveqt-install_docs module-qtsensors-install_docs module-qtimageformats-install_docs module-qtscript-install_docs module-qtquick1-install_docs

module-qtbase-uninstall_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
module-qtx11extras-uninstall_docs: module-qtbase-uninstall_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
module-qtsvg-uninstall_docs: module-qtbase-uninstall_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
module-qtactiveqt-uninstall_docs: module-qtbase-uninstall_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
module-qtsensors-uninstall_docs: module-qtbase-uninstall_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
module-qtimageformats-uninstall_docs: module-qtbase-uninstall_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
module-qtscript-uninstall_docs: module-qtbase-uninstall_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
module-qtquick1-uninstall_docs: module-qtscript-uninstall_docs module-qtsvg-uninstall_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
uninstall_docs: module-qtbase-uninstall_docs module-qtx11extras-uninstall_docs module-qtsvg-uninstall_docs module-qtactiveqt-uninstall_docs module-qtsensors-uninstall_docs module-qtimageformats-uninstall_docs module-qtscript-uninstall_docs module-qtquick1-uninstall_docs

module-qtbase-qch_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
module-qtx11extras-qch_docs: module-qtbase-qch_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
module-qtsvg-qch_docs: module-qtbase-qch_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
module-qtactiveqt-qch_docs: module-qtbase-qch_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
module-qtsensors-qch_docs: module-qtbase-qch_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
module-qtimageformats-qch_docs: module-qtbase-qch_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
module-qtscript-qch_docs: module-qtbase-qch_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
module-qtquick1-qch_docs: module-qtscript-qch_docs module-qtsvg-qch_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
qch_docs: module-qtbase-qch_docs module-qtx11extras-qch_docs module-qtsvg-qch_docs module-qtactiveqt-qch_docs module-qtsensors-qch_docs module-qtimageformats-qch_docs module-qtscript-qch_docs module-qtquick1-qch_docs

module-qtbase-prepare_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
module-qtx11extras-prepare_docs: module-qtbase-prepare_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
module-qtsvg-prepare_docs: module-qtbase-prepare_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
module-qtactiveqt-prepare_docs: module-qtbase-prepare_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
module-qtsensors-prepare_docs: module-qtbase-prepare_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
module-qtimageformats-prepare_docs: module-qtbase-prepare_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
module-qtscript-prepare_docs: module-qtbase-prepare_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
module-qtquick1-prepare_docs: module-qtscript-prepare_docs module-qtsvg-prepare_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
prepare_docs: module-qtbase-prepare_docs module-qtx11extras-prepare_docs module-qtsvg-prepare_docs module-qtactiveqt-prepare_docs module-qtsensors-prepare_docs module-qtimageformats-prepare_docs module-qtscript-prepare_docs module-qtquick1-prepare_docs

module-qtbase-generate_docs:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
module-qtx11extras-generate_docs: module-qtbase-generate_docs
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
module-qtsvg-generate_docs: module-qtbase-generate_docs
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
module-qtactiveqt-generate_docs: module-qtbase-generate_docs
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
module-qtsensors-generate_docs: module-qtbase-generate_docs
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
module-qtimageformats-generate_docs: module-qtbase-generate_docs
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
module-qtscript-generate_docs: module-qtbase-generate_docs
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
module-qtquick1-generate_docs: module-qtscript-generate_docs module-qtsvg-generate_docs
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
generate_docs: module-qtbase-generate_docs module-qtx11extras-generate_docs module-qtsvg-generate_docs module-qtactiveqt-generate_docs module-qtsensors-generate_docs module-qtimageformats-generate_docs module-qtscript-generate_docs module-qtquick1-generate_docs

module-qtbase-check:
	@test -d qtbase/ || mkdir -p qtbase/
	cd qtbase/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtbase/qtbase.pro -o Makefile ) && $(MAKE) -f Makefile check
module-qtx11extras-check: module-qtbase-check
	@test -d qtx11extras/ || mkdir -p qtx11extras/
	cd qtx11extras/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtx11extras/qtx11extras.pro -o Makefile ) && $(MAKE) -f Makefile check
module-qtsvg-check: module-qtbase-check
	@test -d qtsvg/ || mkdir -p qtsvg/
	cd qtsvg/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsvg/qtsvg.pro -o Makefile ) && $(MAKE) -f Makefile check
module-qtactiveqt-check: module-qtbase-check
	@test -d qtactiveqt/ || mkdir -p qtactiveqt/
	cd qtactiveqt/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtactiveqt/qtactiveqt.pro -o Makefile ) && $(MAKE) -f Makefile check
module-qtsensors-check: module-qtbase-check
	@test -d qtsensors/ || mkdir -p qtsensors/
	cd qtsensors/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtsensors/qtsensors.pro -o Makefile ) && $(MAKE) -f Makefile check
module-qtimageformats-check: module-qtbase-check
	@test -d qtimageformats/ || mkdir -p qtimageformats/
	cd qtimageformats/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtimageformats/qtimageformats.pro -o Makefile ) && $(MAKE) -f Makefile check
module-qtscript-check: module-qtbase-check
	@test -d qtscript/ || mkdir -p qtscript/
	cd qtscript/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtscript/qtscript.pro -o Makefile ) && $(MAKE) -f Makefile check
module-qtquick1-check: module-qtscript-check module-qtsvg-check
	@test -d qtquick1/ || mkdir -p qtquick1/
	cd qtquick1/ && ( test -e Makefile || $(QMAKE) /Users/kkheller/Documents/qt5_github_repo/qtquick1/qtquick1.pro -o Makefile ) && $(MAKE) -f Makefile check
check: module-qtbase-check module-qtx11extras-check module-qtsvg-check module-qtactiveqt-check module-qtsensors-check module-qtimageformats-check module-qtscript-check module-qtquick1-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

