/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "5.1.1"

#define QTSENSORS_VERSION 0x050101

#endif // QT_QTSENSORS_VERSION_H
