/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "5.1.1"

#define QTUITOOLS_VERSION 0x050101

#endif // QT_QTUITOOLS_VERSION_H
